DROP TABLE IF EXISTS SUPERHEROE;
DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE SUPERHEROE(
    id INT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIOS(
    id INT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(50) NOT NULL
)